/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;
import java.util.Scanner;

public class App {
    
    
    public String getGreeting() {
        return "欢迎使用";
    }
    
     public static void exit(){
        System.out.println("----------------退出---------------");
        System.out.println("您已退出");
    }
    
    
    /**
     * 任务管理功能菜单
     * @return 键盘输入的功能操作序号
     */
    public static int chooseFunction() {
        System.out.println("-------------待办事项管理------------");
        System.out.println("1.查看任务");
        System.out.println("2.增加任务");
        System.out.println("3.删除任务");
        System.out.println("4.标记完成任务");
        System.out.println("5.退出");
        
        System.out.println("请输入要执行的操作序号：");
        //接收键盘输入的功能选项序号
        Scanner sc = new Scanner(System.in);
        int choose = sc.nextInt();
        return choose;
    }
    
    
    public static void printTask(int[] index, String[] title, String[] deadline, boolean[] status) {
        int usrId =0;
        //列表顶部
        System.out.println("---------------------------查看任务--------------------------");
        System.out.println("任务序号        任务内容    截止时间    是否完成");
        //列表中部
//        for (int i = 0; i < this.index.length; i++) {
//            System.out.println(index[i]+"    "+title[i]+"    "+deadline[i]+"    "+status[i]);
//        }
        //列表底部
        System.out.println("-------------------------------------------------------------");
        
    }

    
    
    public void addItem(){
       
        
        
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
         


//        //通过while循环进行功能重复选择操作
//        while (true) {
//            //打印功能菜单操作,接收键盘输入的功能选项序号
//            int choose = chooseFunction();
//            //执行序号对应的功能
//            switch (choose) {
//                case 1://查看任务
//                    printTask(index, title, deadline, status);
//                    break;
//                case 2://增加任务
//                    addItem(index, title, deadline, status);
//                    break;
//                case 3://删除任务
//                    deleteItem(index);
//                    break;
//                case 4://标记完成任务
//                    addItem(index);
//                    break;
//                case 5://退出
//                    exit();
//                    return;
//                default:
//                    System.out.println("----------------------------------");
//                    System.out.println("功能选择有误，请输入正确的功能序号!");
//                    break;
//            }
//        }
        
    }
}
>>>>>>> origin/master
