/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int usrId = 1;
        FileIO f = new FileIO();
        //f.saveFile(, usrId);
    }
}
